name: request_handling_app
description: Request Handling Workflow Prototype
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.0
  http: ^0.13.6
  socket_io_client: ^2.0.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/avatarman.png
    - assets/avatarwoman.webp
